name: Code Analysis

on:
  pull_request: null
  push:
    branches:
      - master

env:
  COMPOSER_ROOT_VERSION: dev-master

jobs:
  prepare_env:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_GITHUB }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS_GITHUB }}

      - name: Composer install
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist"

      - name: Install Symplify easy-ci
        run: composer require --dev symplify/easy-ci --no-interaction --no-progress --ansi --prefer-stable --prefer-dist

      - id: output_php
        run: echo "::set-output name=matrix::$(vendor/bin/easy-ci php-versions-json)"

    outputs:
      php: ${{ steps.output_php.outputs.matrix }}

  unit_tests:
    needs: prepare_env

    strategy:
      fail-fast: false
      matrix:
        php: ${{ fromJson(needs.prepare_env.outputs.php) }}

    name: Test on PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Composer install
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist"

      - name: Unit tests
        run: composer test-phpunit
